name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: pizza/pizza.tex
- name: Upload PDF file 
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: pizza/pizza.pdf
